CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;
CREATE TABLE DATA_SALARIES(work_year INT,
experience_level INT ,
employment_type VARCHAR(20),
job_title VARCHAR (100),
salary INT ,
salary_currency VARCHAR (50),
salary_in_usd INT,
employee_residence VARCHAR(100),
remote_ratio INT,
company_location VARCHAR(100),
company_size VARCHAR (20));
SELECT * FROM SALARIES;

/** 1. THIRD HIGHEST SALARY **/
WITH SALARYRANK AS (SELECT SALARY,DENSE_RANK()OVER(ORDER BY SALARY DESC) AS RAN 
FROM SALARIES)
SELECT SALARY FROM SALARYRANK WHERE RAN = 2;

SELECT DISTINCT SALARY FROM SALARIES
ORDER BY SALARY DESC
LIMIT 1 OFFSET 2;

SELECT SALARY,DENSE_RANK()OVER(ORDER BY SALARY DESC) AS RAN 
FROM SALARIES;