SHOW DATABASES;
USE CAMPUSX;
SHOW TABLES;
SELECT*FROM HR_EMP_TABLE;
SELECT*FROM PROJ_ASSIGN;

/*EMP ASSIGNED TO PROJECT FROM HEAELTHCARE DEPARTMENT*/
SELECT E.EMP_ID,P.PROJ_ID,E.FIRST_NAME,E.DEPT FROM HR_EMP_TABLE E
INNER JOIN PROJ_ASSIGN P ON E.EMP_ID = P.EMP_ID
WHERE DEPT IN ('HEALTHCARE');

/* Your manager wants the details of the ongoing projects along with the  number of employees working on them.*/
SELECT * FROM PROJ_RECORDS;
SELECT P.PROJ_ID,R.PROJ_NAME, R.STATUS , R.DOMAIN FROM PROJ_RECORDS R
LEFT JOIN PROJ_ASSIGN P USING (PROJ_ID);

/* Your manager wants the details of each employee along with the 
number of projects assigned to them*/
SELECT E.EMP_ID,E.FIRST_NAME, E.DEPT,E.ROLE , COUNT(DISTINCT P.PROJ_ID) AS `PROJ_COUNT`
FROM PROJ_ASSIGN P
RIGHT JOIN HR_EMP_TABLE E ON E.EMP_ID = P.EMP_ID
WHERE E.ROLE NOT IN ("MANAGER","PRESIDENT","CEO")
GROUP BY E.EMP_ID,E.FIRST_NAME, E.DEPT,E.ROLE
ORDER BY PROJ_COUNT;

/* Your manager wants you to identify the number of employees 
reporting to each manager including the President and the CEO.*/
SELECT E.FIRST_NAME,COUNT(E.EMP_ID) AS EMP_COUNT , R.ROLE 
FROM HR_EMP_TABLE E
INNER JOIN HR_EMP_TABLE R
ON E.EMP_ID = R.EMP_ID
AND E.EMP_ID != R.`MANAGER ID`
WHERE E.ROLE IN ("MANAGER","PRESIDENT","CEO")
GROUP BY E.EMP_ID, E.FIRST_NAME,R.ROLE
ORDER BY E.EMP_ID;

 
