USE EMPLOYEE;
SHOW TABLES;
SELECT * FROM WORKER;
SELECT W.FIRST_NAME , COUNT(*) AS UNIQ FROM WORKER W INNER JOIN WORKER T ON W.WORKER_ID = T.WORKER_ID 
GROUP BY FIRST_NAME 
HAVING COUNT(*) = 1;

SELECT WORKER_ID,FIRST_NAME FROM WORKER WHERE MOD(WORKER_ID,2) != 0;
SELECT WORKER_ID , FIRST_NAME FROM WORKER WHERE MOD(WORKER_ID,2)=0;

SELECT FIRST_NAME, COUNT(*) AS UNIQ FROM WORKER GROUP BY FIRST_NAME HAVING COUNT(*) > 1; 

SELECT FIRST_NAME, SALARY FROM WORKER ORDER BY SALARY DESC LIMIT 4,1;

SELECT * FROM WORKER W1 WHERE 4 = (SELECT COUNT(DISTINCT(W2.SALARY)) FROM WORKER W2 WHERE W2.SALARY >= W1.SALARY);


SELECT W1.* FROM WORKER W1 CROSS JOIN WORKER W2;
SELECT W1.* FROM WORKER W1,WORKER W2 WHERE W1.SALARY = W2.SALARY AND W1.WORKER_ID != W2.WORKER_ID;

SELECT MAX(SALARY) FROM WORKER WHERE SALARY NOT IN (SELECT MAX(SALARY) FROM WORKER );
SELECT FIRST_NAME, SALARY FROM WORKER ORDER BY SALARY DESC LIMIT 5;

SELECT MAX(SALARY) FROM WORKER;