
USE EMPLOYEE;
SHOW TABLES;
SELECT* FROM SALARIES;
-- Determine the top N percent of employees based on salary 0 to highest and 1 to lowest for desc order like top 1 % salary holders are 1398-- 
WITH RANKED_EMPLOYEE AS (SELECT JOB_TITLE,SALARY,
PERCENT_RANK() OVER (ORDER BY SALARY DESC) AS PERCENTILE
FROM SALARIES)
SELECT JOB_TITLE , SALARY,PERCENTILE
FROM RANKED_EMPLOYEE
WHERE PERCENTILE < 0.1;

-- MAX SALARY FROM E 
-- MAX SALARY FROM E 
SELECT *,MAX(SALARY) OVER (PARTITION BY JOB_TITLE ORDER BY SALARY DESC) AS MAX_OF_DEPT FROM SALARIES;

SELECT MAX(SALARY) AS SALARY , JOB_TITLE FROM SALARIES
GROUP BY JOB_TITLE
ORDER BY SALARY DESC;

SELECT JOB_TITLE, SALARY FROM SALARIES S WHERE SALARY = (SELECT MAX(SALARY) FROM SALARIES WHERE JOB_TITLE = S.JOB_TITLE );