USE GEEKS;
SELECT * 
FROM EMPLOYEE_DB
ORDER BY DEPT;

SELECT FIRST_NAME, GENDER, ROLE, EXP, SALARY,
ROW_NUMBER() OVER (PARTITION BY ROLE ORDER BY SALARY) AS RN ,
DENSE_RANK() OVER (PARTITION BY ROLE ORDER BY SALARY ) AS DENSE_RN
FROM EMPLOYEE_DB;

WITH CTE AS (SELECT CONTINENT , SUM(SALARY) AS SUM_SALARY
FROM EMPLOYEE_DB 
GROUP BY CONTINENT)
SELECT * 
FROM CTE 
ORDER BY SUM_SALARY ASC;

/** date and time **/
USE GEEKS;
SHOW TABLES;
ALTER TABLE GEEKS.SUPERSTORE
RENAME TO SAMPLESTORE;
SELECT COUNT(*) FROM SAMPLESTORE;
DESCRIBE SAMPLESTORE;
/* TOTAL SALES FOR EACH YEAR */

 SELECT YEAR(`order date`) AS YEAR , SUM(SALES) AS TOTAL_SALES
 FROM SAMPLESTORE
 GROUP BY YEAR(`order date`)
 ORDER BY YEAR;
 SELECT * FROM SAMPLESTORE;
 SELECT YEAR(`ORDER DATE`) AS OrderYear
FROM SampleStore;
set sql_safe_updates = 0
UPDATE SampleStore
SET `SHIP DATE` = DATE_FORMAT(STR_TO_DATE(`SHIP DATE`, '%d-%m-%Y'), '%Y-%m-%d')
WHERE `SHIP DATE` IS NOT NULL;
describe samplestore;
UPDATE SampleStore
SET `SHIP DATE` = STR_TO_DATE(`SHIP DATE`, '%Y-%m-%d')
WHERE `SHIP DATE` IS NOT NULL;

/** no.of empl in each dept **/
USE GEEKS;
SHOW TABLES;
SELECT * FROM EMPLOYEE_DB;
alter table employee_db
change ï»¿EMP_ID EMP varchar(100);
SELECT DEPT, COUNT(*) AS TOTAL_EMP 
FROM EMPLOYEE_DB
GROUP BY DEPT;

/** avg salary by drpt **/
SELECT * FROM EMPLOYEE_DB;
SELECT DEPT , AVG(SALARY) AS AVG_DEPT_SAL
FROM EMPLOYEE_DB
GROUP BY DEPT;

/** highest salary from dept**/
SELECT E.DEPT ,E.EMP , E.SALARY 
FROM EMPLOYEE_DB E WHERE SALARY =(SELECT MAX(SALARY) FROM EMPLOYEE_DB WHERE DEPT = E.DEPT);

 






 
 SELECT YEAR ( "ORDER DATE") FROM SAMPLESTORE;
